sudo: required

services: docker

env:
  DOCKER_USERNAME: yukiueta
  DOCKER_ACCESS_TOKEN: 0f10ca45-466c-4372-840e-6a14c050c52c

before_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test